/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Nat;
export const Timestamp = IDL.Int;
export const SubscriptionStatus = IDL.Variant({
  'trial' : IDL.Null,
  'active' : IDL.Null,
  'expired' : IDL.Null,
});
export const SubscriptionPublic = IDL.Record({
  'status' : SubscriptionStatus,
  'subscriptionEndDate' : IDL.Opt(Timestamp),
  'userId' : UserId,
  'amountPaid' : IDL.Nat,
  'subscriptionStartDate' : IDL.Opt(Timestamp),
  'trialStartDate' : IDL.Opt(Timestamp),
  'planName' : IDL.Text,
});
export const AllocationId = IDL.Nat;
export const AllocationPublic = IDL.Record({
  'id' : AllocationId,
  'name' : IDL.Text,
  'allocatedAmount' : IDL.Nat,
  'spentAmount' : IDL.Nat,
});
export const AuditAction = IDL.Variant({
  'generateReport' : IDL.Null,
  'deleteTransaction' : IDL.Null,
  'other' : IDL.Null,
  'editTransaction' : IDL.Null,
  'login' : IDL.Null,
  'addTransaction' : IDL.Null,
});
export const AuditLogId = IDL.Nat;
export const AuditLog = IDL.Record({
  'id' : AuditLogId,
  'action' : AuditAction,
  'userEmail' : IDL.Text,
  'userId' : UserId,
  'description' : IDL.Text,
  'timestamp' : Timestamp,
});
export const CoaReportType = IDL.Variant({
  'notesToFS' : IDL.Null,
  'inventoryReport' : IDL.Null,
  'asrp' : IDL.Null,
  'qsrp' : IDL.Null,
  'raaf' : IDL.Null,
  'budgetVsActual' : IDL.Null,
});
export const CoaReportId = IDL.Nat;
export const CoaReportStatus = IDL.Variant({
  'pendingReview' : IDL.Null,
  'submitted' : IDL.Null,
  'needsRevision' : IDL.Null,
  'approved' : IDL.Null,
  'draft' : IDL.Null,
});
export const CoaReportPublic = IDL.Record({
  'id' : CoaReportId,
  'status' : CoaReportStatus,
  'fiscalYear' : IDL.Nat,
  'quarter' : IDL.Opt(IDL.Nat),
  'createdAt' : Timestamp,
  'submittedAt' : IDL.Opt(Timestamp),
  'deadline' : IDL.Opt(Timestamp),
  'reportType' : CoaReportType,
  'notes' : IDL.Text,
});
export const TransactionId = IDL.Nat;
export const ProjectId = IDL.Nat;
export const DocumentId = IDL.Nat;
export const Document = IDL.Record({
  'id' : DocumentId,
  'linkedTransactionId' : IDL.Opt(TransactionId),
  'linkedProjectId' : IDL.Opt(ProjectId),
  'fileName' : IDL.Text,
  'fileType' : IDL.Text,
  'storageKey' : IDL.Text,
  'uploadedAt' : Timestamp,
  'uploadedBy' : UserId,
});
export const NotificationType = IDL.Variant({
  'budgetAlert' : IDL.Null,
  'coaDeadline' : IDL.Null,
  'missingReceipt' : IDL.Null,
  'pendingApproval' : IDL.Null,
  'subscriptionReminder' : IDL.Null,
});
export const NotificationId = IDL.Nat;
export const NotificationPublic = IDL.Record({
  'id' : NotificationId,
  'title' : IDL.Text,
  'notifType' : NotificationType,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
});
export const AddProjectInput = IDL.Record({
  'endDate' : IDL.Opt(Timestamp),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'budgetAllocation' : IDL.Nat,
  'startDate' : Timestamp,
});
export const ProjectStatus = IDL.Variant({
  'completed' : IDL.Null,
  'ongoing' : IDL.Null,
  'planning' : IDL.Null,
});
export const ProjectPublic = IDL.Record({
  'id' : ProjectId,
  'status' : ProjectStatus,
  'endDate' : IDL.Opt(Timestamp),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'totalExpenses' : IDL.Nat,
  'budgetAllocation' : IDL.Nat,
  'updatedAt' : Timestamp,
  'startDate' : Timestamp,
});
export const SupplierId = IDL.Nat;
export const PurchaseId = IDL.Nat;
export const Purchase = IDL.Record({
  'date' : Timestamp,
  'description' : IDL.Text,
  'purchaseId' : PurchaseId,
  'amount' : IDL.Nat,
  'supplierId' : SupplierId,
  'transactionId' : TransactionId,
});
export const SupplierPublic = IDL.Record({
  'id' : SupplierId,
  'tin' : IDL.Text,
  'isVatRegistered' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'contactPerson' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const PaymentMethod = IDL.Variant({
  'cash' : IDL.Null,
  'check' : IDL.Null,
  'bankTransfer' : IDL.Null,
  'gcash' : IDL.Null,
});
export const CheckStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'issued' : IDL.Null,
  'pendingIssuance' : IDL.Null,
  'cleared' : IDL.Null,
});
export const CheckDetailsPublic = IDL.Record({
  'status' : CheckStatus,
  'bankName' : IDL.Text,
  'checkNumber' : IDL.Opt(IDL.Text),
  'checkDate' : Timestamp,
  'payee' : IDL.Text,
  'purpose' : IDL.Text,
});
export const TransactionType = IDL.Variant({
  'projectExpenses' : IDL.Null,
  'expenses' : IDL.Null,
  'cashAdvance' : IDL.Null,
  'reimbursement' : IDL.Null,
  'income' : IDL.Null,
});
export const AddTransactionInput = IDL.Record({
  'paymentMethod' : PaymentMethod,
  'date' : Timestamp,
  'description' : IDL.Text,
  'projectId' : IDL.Opt(ProjectId),
  'checkDetails' : IDL.Opt(CheckDetailsPublic),
  'txType' : TransactionType,
  'receiptId' : IDL.Opt(DocumentId),
  'amount' : IDL.Nat,
  'supplierId' : IDL.Opt(SupplierId),
});
export const TransactionPublic = IDL.Record({
  'id' : TransactionId,
  'paymentMethod' : PaymentMethod,
  'userId' : UserId,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'projectId' : IDL.Opt(ProjectId),
  'checkDetails' : IDL.Opt(CheckDetailsPublic),
  'txType' : TransactionType,
  'receiptId' : IDL.Opt(DocumentId),
  'amount' : IDL.Nat,
  'supplierId' : IDL.Opt(SupplierId),
});
export const Role = IDL.Variant({
  'chairperson' : IDL.Null,
  'treasurer' : IDL.Null,
});
export const UserPublic = IDL.Record({
  'id' : UserId,
  'lastActivity' : Timestamp,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : Role,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
});
export const CreateUserResult = IDL.Variant({
  'ok' : UserPublic,
  'err' : IDL.Text,
});
export const AuditFilter = IDL.Record({
  'action' : IDL.Opt(AuditAction),
  'userId' : IDL.Opt(UserId),
  'toDate' : IDL.Opt(Timestamp),
  'fromDate' : IDL.Opt(Timestamp),
});
export const Budget = IDL.Record({
  'fiscalYear' : IDL.Nat,
  'totalBudget' : IDL.Nat,
});
export const SupportingDocPublic = IDL.Record({
  'isSubmitted' : IDL.Bool,
  'linkedReportId' : CoaReportId,
  'docType' : IDL.Text,
});
export const TransactionFilter = IDL.Record({
  'paymentMethod' : IDL.Opt(PaymentMethod),
  'toDate' : IDL.Opt(Timestamp),
  'projectId' : IDL.Opt(ProjectId),
  'fromDate' : IDL.Opt(Timestamp),
  'txType' : IDL.Opt(TransactionType),
});
export const LoginResult = IDL.Variant({
  'ok' : IDL.Record({ 'token' : IDL.Text, 'user' : UserPublic }),
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  'activateSubscription' : IDL.Func(
      [UserId, Timestamp, IDL.Nat],
      [IDL.Opt(SubscriptionPublic)],
      [],
    ),
  'addAllocation' : IDL.Func([IDL.Text, IDL.Nat], [AllocationPublic], []),
  'addAuditLog' : IDL.Func(
      [UserId, IDL.Text, AuditAction, IDL.Text],
      [AuditLog],
      [],
    ),
  'addCoaReport' : IDL.Func(
      [CoaReportType, IDL.Nat, IDL.Opt(IDL.Nat), IDL.Opt(Timestamp)],
      [CoaReportPublic],
      [],
    ),
  'addDocument' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        UserId,
        IDL.Opt(TransactionId),
        IDL.Opt(ProjectId),
        IDL.Text,
      ],
      [Document],
      [],
    ),
  'addNotification' : IDL.Func(
      [UserId, NotificationType, IDL.Text, IDL.Text],
      [NotificationPublic],
      [],
    ),
  'addProject' : IDL.Func([AddProjectInput], [ProjectPublic], []),
  'addPurchase' : IDL.Func(
      [SupplierId, TransactionId, IDL.Nat, Timestamp, IDL.Text],
      [Purchase],
      [],
    ),
  'addSupplier' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool, IDL.Text, IDL.Text, IDL.Text],
      [SupplierPublic],
      [],
    ),
  'addTransaction' : IDL.Func(
      [AddTransactionInput, UserId],
      [TransactionPublic],
      [],
    ),
  'checkSubscriptionStatus' : IDL.Func(
      [UserId],
      [IDL.Opt(SubscriptionStatus)],
      ['query'],
    ),
  'createSubscription' : IDL.Func(
      [UserId, IDL.Text, IDL.Bool],
      [SubscriptionPublic],
      [],
    ),
  'createUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Role],
      [CreateUserResult],
      [],
    ),
  'deleteAllocation' : IDL.Func([AllocationId], [IDL.Bool], []),
  'deleteDocument' : IDL.Func([DocumentId], [IDL.Bool], []),
  'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
  'deleteSupplier' : IDL.Func([SupplierId], [IDL.Bool], []),
  'deleteTransaction' : IDL.Func([TransactionId], [IDL.Bool], []),
  'dismissNotification' : IDL.Func([NotificationId], [IDL.Bool], []),
  'expireSubscription' : IDL.Func([UserId], [IDL.Opt(SubscriptionPublic)], []),
  'getActiveProjectsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getAllocations' : IDL.Func([], [IDL.Vec(AllocationPublic)], ['query']),
  'getAuditLogs' : IDL.Func(
      [IDL.Opt(AuditFilter)],
      [IDL.Vec(AuditLog)],
      ['query'],
    ),
  'getBudget' : IDL.Func([], [IDL.Opt(Budget)], ['query']),
  'getCoaReports' : IDL.Func([], [IDL.Vec(CoaReportPublic)], ['query']),
  'getDashboardSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'activeProjectsCount' : IDL.Nat,
          'totalIncome' : IDL.Nat,
          'totalExpenses' : IDL.Nat,
          'totalBudget' : IDL.Opt(IDL.Nat),
          'remainingBalance' : IDL.Opt(IDL.Nat),
        }),
      ],
      ['query'],
    ),
  'getDocumentById' : IDL.Func([DocumentId], [IDL.Opt(Document)], ['query']),
  'getDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
  'getDocumentsByProject' : IDL.Func(
      [ProjectId],
      [IDL.Vec(Document)],
      ['query'],
    ),
  'getDocumentsByTransaction' : IDL.Func(
      [TransactionId],
      [IDL.Vec(Document)],
      ['query'],
    ),
  'getNotifications' : IDL.Func(
      [UserId],
      [IDL.Vec(NotificationPublic)],
      ['query'],
    ),
  'getOverdueReports' : IDL.Func([], [IDL.Vec(CoaReportPublic)], ['query']),
  'getProjectById' : IDL.Func([ProjectId], [IDL.Opt(ProjectPublic)], ['query']),
  'getProjects' : IDL.Func([], [IDL.Vec(ProjectPublic)], ['query']),
  'getPurchasesBySupplier' : IDL.Func(
      [SupplierId],
      [IDL.Vec(Purchase)],
      ['query'],
    ),
  'getRecentLogs' : IDL.Func([IDL.Nat], [IDL.Vec(AuditLog)], ['query']),
  'getRemainingBalance' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
  'getSubscription' : IDL.Func(
      [UserId],
      [IDL.Opt(SubscriptionPublic)],
      ['query'],
    ),
  'getSupplierById' : IDL.Func(
      [SupplierId],
      [IDL.Opt(SupplierPublic)],
      ['query'],
    ),
  'getSuppliers' : IDL.Func([], [IDL.Vec(SupplierPublic)], ['query']),
  'getSupportingDocs' : IDL.Func(
      [CoaReportId],
      [IDL.Vec(SupportingDocPublic)],
      ['query'],
    ),
  'getTotalExpenses' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalIncome' : IDL.Func([], [IDL.Nat], ['query']),
  'getTransactionById' : IDL.Func(
      [TransactionId],
      [IDL.Opt(TransactionPublic)],
      ['query'],
    ),
  'getTransactions' : IDL.Func(
      [IDL.Opt(TransactionFilter)],
      [IDL.Vec(TransactionPublic)],
      ['query'],
    ),
  'getUnreadCount' : IDL.Func([UserId], [IDL.Nat], ['query']),
  'getUserById' : IDL.Func([UserId], [IDL.Opt(UserPublic)], ['query']),
  'getUserByToken' : IDL.Func([IDL.Text], [IDL.Opt(UserPublic)], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'logout' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'markAsRead' : IDL.Func([NotificationId], [IDL.Bool], []),
  'setBudget' : IDL.Func([IDL.Nat, IDL.Nat], [Budget], []),
  'submitSupportingDoc' : IDL.Func([CoaReportId, IDL.Text], [IDL.Bool], []),
  'updateAllocation' : IDL.Func(
      [AllocationId, IDL.Text, IDL.Nat],
      [IDL.Opt(AllocationPublic)],
      [],
    ),
  'updateCoaReport' : IDL.Func(
      [CoaReportId, CoaReportStatus, IDL.Text],
      [IDL.Opt(CoaReportPublic)],
      [],
    ),
  'updateProject' : IDL.Func(
      [ProjectId, AddProjectInput],
      [IDL.Opt(ProjectPublic)],
      [],
    ),
  'updateProjectStatus' : IDL.Func(
      [ProjectId, ProjectStatus],
      [IDL.Opt(ProjectPublic)],
      [],
    ),
  'updateSubscription' : IDL.Func(
      [UserId, SubscriptionStatus, IDL.Opt(Timestamp), IDL.Nat],
      [IDL.Opt(SubscriptionPublic)],
      [],
    ),
  'updateSupplier' : IDL.Func(
      [SupplierId, IDL.Text, IDL.Text, IDL.Bool, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(SupplierPublic)],
      [],
    ),
  'updateTransaction' : IDL.Func(
      [TransactionId, AddTransactionInput],
      [IDL.Opt(TransactionPublic)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Nat;
  const Timestamp = IDL.Int;
  const SubscriptionStatus = IDL.Variant({
    'trial' : IDL.Null,
    'active' : IDL.Null,
    'expired' : IDL.Null,
  });
  const SubscriptionPublic = IDL.Record({
    'status' : SubscriptionStatus,
    'subscriptionEndDate' : IDL.Opt(Timestamp),
    'userId' : UserId,
    'amountPaid' : IDL.Nat,
    'subscriptionStartDate' : IDL.Opt(Timestamp),
    'trialStartDate' : IDL.Opt(Timestamp),
    'planName' : IDL.Text,
  });
  const AllocationId = IDL.Nat;
  const AllocationPublic = IDL.Record({
    'id' : AllocationId,
    'name' : IDL.Text,
    'allocatedAmount' : IDL.Nat,
    'spentAmount' : IDL.Nat,
  });
  const AuditAction = IDL.Variant({
    'generateReport' : IDL.Null,
    'deleteTransaction' : IDL.Null,
    'other' : IDL.Null,
    'editTransaction' : IDL.Null,
    'login' : IDL.Null,
    'addTransaction' : IDL.Null,
  });
  const AuditLogId = IDL.Nat;
  const AuditLog = IDL.Record({
    'id' : AuditLogId,
    'action' : AuditAction,
    'userEmail' : IDL.Text,
    'userId' : UserId,
    'description' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const CoaReportType = IDL.Variant({
    'notesToFS' : IDL.Null,
    'inventoryReport' : IDL.Null,
    'asrp' : IDL.Null,
    'qsrp' : IDL.Null,
    'raaf' : IDL.Null,
    'budgetVsActual' : IDL.Null,
  });
  const CoaReportId = IDL.Nat;
  const CoaReportStatus = IDL.Variant({
    'pendingReview' : IDL.Null,
    'submitted' : IDL.Null,
    'needsRevision' : IDL.Null,
    'approved' : IDL.Null,
    'draft' : IDL.Null,
  });
  const CoaReportPublic = IDL.Record({
    'id' : CoaReportId,
    'status' : CoaReportStatus,
    'fiscalYear' : IDL.Nat,
    'quarter' : IDL.Opt(IDL.Nat),
    'createdAt' : Timestamp,
    'submittedAt' : IDL.Opt(Timestamp),
    'deadline' : IDL.Opt(Timestamp),
    'reportType' : CoaReportType,
    'notes' : IDL.Text,
  });
  const TransactionId = IDL.Nat;
  const ProjectId = IDL.Nat;
  const DocumentId = IDL.Nat;
  const Document = IDL.Record({
    'id' : DocumentId,
    'linkedTransactionId' : IDL.Opt(TransactionId),
    'linkedProjectId' : IDL.Opt(ProjectId),
    'fileName' : IDL.Text,
    'fileType' : IDL.Text,
    'storageKey' : IDL.Text,
    'uploadedAt' : Timestamp,
    'uploadedBy' : UserId,
  });
  const NotificationType = IDL.Variant({
    'budgetAlert' : IDL.Null,
    'coaDeadline' : IDL.Null,
    'missingReceipt' : IDL.Null,
    'pendingApproval' : IDL.Null,
    'subscriptionReminder' : IDL.Null,
  });
  const NotificationId = IDL.Nat;
  const NotificationPublic = IDL.Record({
    'id' : NotificationId,
    'title' : IDL.Text,
    'notifType' : NotificationType,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
  });
  const AddProjectInput = IDL.Record({
    'endDate' : IDL.Opt(Timestamp),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'budgetAllocation' : IDL.Nat,
    'startDate' : Timestamp,
  });
  const ProjectStatus = IDL.Variant({
    'completed' : IDL.Null,
    'ongoing' : IDL.Null,
    'planning' : IDL.Null,
  });
  const ProjectPublic = IDL.Record({
    'id' : ProjectId,
    'status' : ProjectStatus,
    'endDate' : IDL.Opt(Timestamp),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'totalExpenses' : IDL.Nat,
    'budgetAllocation' : IDL.Nat,
    'updatedAt' : Timestamp,
    'startDate' : Timestamp,
  });
  const SupplierId = IDL.Nat;
  const PurchaseId = IDL.Nat;
  const Purchase = IDL.Record({
    'date' : Timestamp,
    'description' : IDL.Text,
    'purchaseId' : PurchaseId,
    'amount' : IDL.Nat,
    'supplierId' : SupplierId,
    'transactionId' : TransactionId,
  });
  const SupplierPublic = IDL.Record({
    'id' : SupplierId,
    'tin' : IDL.Text,
    'isVatRegistered' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'contactPerson' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const PaymentMethod = IDL.Variant({
    'cash' : IDL.Null,
    'check' : IDL.Null,
    'bankTransfer' : IDL.Null,
    'gcash' : IDL.Null,
  });
  const CheckStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'issued' : IDL.Null,
    'pendingIssuance' : IDL.Null,
    'cleared' : IDL.Null,
  });
  const CheckDetailsPublic = IDL.Record({
    'status' : CheckStatus,
    'bankName' : IDL.Text,
    'checkNumber' : IDL.Opt(IDL.Text),
    'checkDate' : Timestamp,
    'payee' : IDL.Text,
    'purpose' : IDL.Text,
  });
  const TransactionType = IDL.Variant({
    'projectExpenses' : IDL.Null,
    'expenses' : IDL.Null,
    'cashAdvance' : IDL.Null,
    'reimbursement' : IDL.Null,
    'income' : IDL.Null,
  });
  const AddTransactionInput = IDL.Record({
    'paymentMethod' : PaymentMethod,
    'date' : Timestamp,
    'description' : IDL.Text,
    'projectId' : IDL.Opt(ProjectId),
    'checkDetails' : IDL.Opt(CheckDetailsPublic),
    'txType' : TransactionType,
    'receiptId' : IDL.Opt(DocumentId),
    'amount' : IDL.Nat,
    'supplierId' : IDL.Opt(SupplierId),
  });
  const TransactionPublic = IDL.Record({
    'id' : TransactionId,
    'paymentMethod' : PaymentMethod,
    'userId' : UserId,
    'date' : Timestamp,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'projectId' : IDL.Opt(ProjectId),
    'checkDetails' : IDL.Opt(CheckDetailsPublic),
    'txType' : TransactionType,
    'receiptId' : IDL.Opt(DocumentId),
    'amount' : IDL.Nat,
    'supplierId' : IDL.Opt(SupplierId),
  });
  const Role = IDL.Variant({
    'chairperson' : IDL.Null,
    'treasurer' : IDL.Null,
  });
  const UserPublic = IDL.Record({
    'id' : UserId,
    'lastActivity' : Timestamp,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : Role,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
  });
  const CreateUserResult = IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text });
  const AuditFilter = IDL.Record({
    'action' : IDL.Opt(AuditAction),
    'userId' : IDL.Opt(UserId),
    'toDate' : IDL.Opt(Timestamp),
    'fromDate' : IDL.Opt(Timestamp),
  });
  const Budget = IDL.Record({
    'fiscalYear' : IDL.Nat,
    'totalBudget' : IDL.Nat,
  });
  const SupportingDocPublic = IDL.Record({
    'isSubmitted' : IDL.Bool,
    'linkedReportId' : CoaReportId,
    'docType' : IDL.Text,
  });
  const TransactionFilter = IDL.Record({
    'paymentMethod' : IDL.Opt(PaymentMethod),
    'toDate' : IDL.Opt(Timestamp),
    'projectId' : IDL.Opt(ProjectId),
    'fromDate' : IDL.Opt(Timestamp),
    'txType' : IDL.Opt(TransactionType),
  });
  const LoginResult = IDL.Variant({
    'ok' : IDL.Record({ 'token' : IDL.Text, 'user' : UserPublic }),
    'err' : IDL.Text,
  });
  
  return IDL.Service({
    'activateSubscription' : IDL.Func(
        [UserId, Timestamp, IDL.Nat],
        [IDL.Opt(SubscriptionPublic)],
        [],
      ),
    'addAllocation' : IDL.Func([IDL.Text, IDL.Nat], [AllocationPublic], []),
    'addAuditLog' : IDL.Func(
        [UserId, IDL.Text, AuditAction, IDL.Text],
        [AuditLog],
        [],
      ),
    'addCoaReport' : IDL.Func(
        [CoaReportType, IDL.Nat, IDL.Opt(IDL.Nat), IDL.Opt(Timestamp)],
        [CoaReportPublic],
        [],
      ),
    'addDocument' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          UserId,
          IDL.Opt(TransactionId),
          IDL.Opt(ProjectId),
          IDL.Text,
        ],
        [Document],
        [],
      ),
    'addNotification' : IDL.Func(
        [UserId, NotificationType, IDL.Text, IDL.Text],
        [NotificationPublic],
        [],
      ),
    'addProject' : IDL.Func([AddProjectInput], [ProjectPublic], []),
    'addPurchase' : IDL.Func(
        [SupplierId, TransactionId, IDL.Nat, Timestamp, IDL.Text],
        [Purchase],
        [],
      ),
    'addSupplier' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, IDL.Text, IDL.Text, IDL.Text],
        [SupplierPublic],
        [],
      ),
    'addTransaction' : IDL.Func(
        [AddTransactionInput, UserId],
        [TransactionPublic],
        [],
      ),
    'checkSubscriptionStatus' : IDL.Func(
        [UserId],
        [IDL.Opt(SubscriptionStatus)],
        ['query'],
      ),
    'createSubscription' : IDL.Func(
        [UserId, IDL.Text, IDL.Bool],
        [SubscriptionPublic],
        [],
      ),
    'createUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Role],
        [CreateUserResult],
        [],
      ),
    'deleteAllocation' : IDL.Func([AllocationId], [IDL.Bool], []),
    'deleteDocument' : IDL.Func([DocumentId], [IDL.Bool], []),
    'deleteProject' : IDL.Func([ProjectId], [IDL.Bool], []),
    'deleteSupplier' : IDL.Func([SupplierId], [IDL.Bool], []),
    'deleteTransaction' : IDL.Func([TransactionId], [IDL.Bool], []),
    'dismissNotification' : IDL.Func([NotificationId], [IDL.Bool], []),
    'expireSubscription' : IDL.Func(
        [UserId],
        [IDL.Opt(SubscriptionPublic)],
        [],
      ),
    'getActiveProjectsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getAllocations' : IDL.Func([], [IDL.Vec(AllocationPublic)], ['query']),
    'getAuditLogs' : IDL.Func(
        [IDL.Opt(AuditFilter)],
        [IDL.Vec(AuditLog)],
        ['query'],
      ),
    'getBudget' : IDL.Func([], [IDL.Opt(Budget)], ['query']),
    'getCoaReports' : IDL.Func([], [IDL.Vec(CoaReportPublic)], ['query']),
    'getDashboardSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'activeProjectsCount' : IDL.Nat,
            'totalIncome' : IDL.Nat,
            'totalExpenses' : IDL.Nat,
            'totalBudget' : IDL.Opt(IDL.Nat),
            'remainingBalance' : IDL.Opt(IDL.Nat),
          }),
        ],
        ['query'],
      ),
    'getDocumentById' : IDL.Func([DocumentId], [IDL.Opt(Document)], ['query']),
    'getDocuments' : IDL.Func([], [IDL.Vec(Document)], ['query']),
    'getDocumentsByProject' : IDL.Func(
        [ProjectId],
        [IDL.Vec(Document)],
        ['query'],
      ),
    'getDocumentsByTransaction' : IDL.Func(
        [TransactionId],
        [IDL.Vec(Document)],
        ['query'],
      ),
    'getNotifications' : IDL.Func(
        [UserId],
        [IDL.Vec(NotificationPublic)],
        ['query'],
      ),
    'getOverdueReports' : IDL.Func([], [IDL.Vec(CoaReportPublic)], ['query']),
    'getProjectById' : IDL.Func(
        [ProjectId],
        [IDL.Opt(ProjectPublic)],
        ['query'],
      ),
    'getProjects' : IDL.Func([], [IDL.Vec(ProjectPublic)], ['query']),
    'getPurchasesBySupplier' : IDL.Func(
        [SupplierId],
        [IDL.Vec(Purchase)],
        ['query'],
      ),
    'getRecentLogs' : IDL.Func([IDL.Nat], [IDL.Vec(AuditLog)], ['query']),
    'getRemainingBalance' : IDL.Func([], [IDL.Opt(IDL.Nat)], ['query']),
    'getSubscription' : IDL.Func(
        [UserId],
        [IDL.Opt(SubscriptionPublic)],
        ['query'],
      ),
    'getSupplierById' : IDL.Func(
        [SupplierId],
        [IDL.Opt(SupplierPublic)],
        ['query'],
      ),
    'getSuppliers' : IDL.Func([], [IDL.Vec(SupplierPublic)], ['query']),
    'getSupportingDocs' : IDL.Func(
        [CoaReportId],
        [IDL.Vec(SupportingDocPublic)],
        ['query'],
      ),
    'getTotalExpenses' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalIncome' : IDL.Func([], [IDL.Nat], ['query']),
    'getTransactionById' : IDL.Func(
        [TransactionId],
        [IDL.Opt(TransactionPublic)],
        ['query'],
      ),
    'getTransactions' : IDL.Func(
        [IDL.Opt(TransactionFilter)],
        [IDL.Vec(TransactionPublic)],
        ['query'],
      ),
    'getUnreadCount' : IDL.Func([UserId], [IDL.Nat], ['query']),
    'getUserById' : IDL.Func([UserId], [IDL.Opt(UserPublic)], ['query']),
    'getUserByToken' : IDL.Func([IDL.Text], [IDL.Opt(UserPublic)], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'logout' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'markAsRead' : IDL.Func([NotificationId], [IDL.Bool], []),
    'setBudget' : IDL.Func([IDL.Nat, IDL.Nat], [Budget], []),
    'submitSupportingDoc' : IDL.Func([CoaReportId, IDL.Text], [IDL.Bool], []),
    'updateAllocation' : IDL.Func(
        [AllocationId, IDL.Text, IDL.Nat],
        [IDL.Opt(AllocationPublic)],
        [],
      ),
    'updateCoaReport' : IDL.Func(
        [CoaReportId, CoaReportStatus, IDL.Text],
        [IDL.Opt(CoaReportPublic)],
        [],
      ),
    'updateProject' : IDL.Func(
        [ProjectId, AddProjectInput],
        [IDL.Opt(ProjectPublic)],
        [],
      ),
    'updateProjectStatus' : IDL.Func(
        [ProjectId, ProjectStatus],
        [IDL.Opt(ProjectPublic)],
        [],
      ),
    'updateSubscription' : IDL.Func(
        [UserId, SubscriptionStatus, IDL.Opt(Timestamp), IDL.Nat],
        [IDL.Opt(SubscriptionPublic)],
        [],
      ),
    'updateSupplier' : IDL.Func(
        [
          SupplierId,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Opt(SupplierPublic)],
        [],
      ),
    'updateTransaction' : IDL.Func(
        [TransactionId, AddTransactionInput],
        [IDL.Opt(TransactionPublic)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };