/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddProjectInput {
  'endDate' : [] | [Timestamp],
  'name' : string,
  'description' : string,
  'budgetAllocation' : bigint,
  'startDate' : Timestamp,
}
export interface AddTransactionInput {
  'paymentMethod' : PaymentMethod,
  'date' : Timestamp,
  'description' : string,
  'projectId' : [] | [ProjectId],
  'checkDetails' : [] | [CheckDetailsPublic],
  'txType' : TransactionType,
  'receiptId' : [] | [DocumentId],
  'amount' : bigint,
  'supplierId' : [] | [SupplierId],
}
export type AllocationId = bigint;
export interface AllocationPublic {
  'id' : AllocationId,
  'name' : string,
  'allocatedAmount' : bigint,
  'spentAmount' : bigint,
}
export type AuditAction = { 'generateReport' : null } |
  { 'deleteTransaction' : null } |
  { 'other' : null } |
  { 'editTransaction' : null } |
  { 'login' : null } |
  { 'addTransaction' : null };
export interface AuditFilter {
  'action' : [] | [AuditAction],
  'userId' : [] | [UserId],
  'toDate' : [] | [Timestamp],
  'fromDate' : [] | [Timestamp],
}
export interface AuditLog {
  'id' : AuditLogId,
  'action' : AuditAction,
  'userEmail' : string,
  'userId' : UserId,
  'description' : string,
  'timestamp' : Timestamp,
}
export type AuditLogId = bigint;
export interface Budget { 'fiscalYear' : bigint, 'totalBudget' : bigint }
export interface CheckDetailsPublic {
  'status' : CheckStatus,
  'bankName' : string,
  'checkNumber' : [] | [string],
  'checkDate' : Timestamp,
  'payee' : string,
  'purpose' : string,
}
export type CheckStatus = { 'cancelled' : null } |
  { 'issued' : null } |
  { 'pendingIssuance' : null } |
  { 'cleared' : null };
export type CoaReportId = bigint;
export interface CoaReportPublic {
  'id' : CoaReportId,
  'status' : CoaReportStatus,
  'fiscalYear' : bigint,
  'quarter' : [] | [bigint],
  'createdAt' : Timestamp,
  'submittedAt' : [] | [Timestamp],
  'deadline' : [] | [Timestamp],
  'reportType' : CoaReportType,
  'notes' : string,
}
export type CoaReportStatus = { 'pendingReview' : null } |
  { 'submitted' : null } |
  { 'needsRevision' : null } |
  { 'approved' : null } |
  { 'draft' : null };
export type CoaReportType = { 'notesToFS' : null } |
  { 'inventoryReport' : null } |
  { 'asrp' : null } |
  { 'qsrp' : null } |
  { 'raaf' : null } |
  { 'budgetVsActual' : null };
export type CreateUserResult = { 'ok' : UserPublic } |
  { 'err' : string };
export interface Document {
  'id' : DocumentId,
  'linkedTransactionId' : [] | [TransactionId],
  'linkedProjectId' : [] | [ProjectId],
  'fileName' : string,
  'fileType' : string,
  'storageKey' : string,
  'uploadedAt' : Timestamp,
  'uploadedBy' : UserId,
}
export type DocumentId = bigint;
export type LoginResult = { 'ok' : { 'token' : string, 'user' : UserPublic } } |
  { 'err' : string };
export type NotificationId = bigint;
export interface NotificationPublic {
  'id' : NotificationId,
  'title' : string,
  'notifType' : NotificationType,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'message' : string,
}
export type NotificationType = { 'budgetAlert' : null } |
  { 'coaDeadline' : null } |
  { 'missingReceipt' : null } |
  { 'pendingApproval' : null } |
  { 'subscriptionReminder' : null };
export type PaymentMethod = { 'cash' : null } |
  { 'check' : null } |
  { 'bankTransfer' : null } |
  { 'gcash' : null };
export type ProjectId = bigint;
export interface ProjectPublic {
  'id' : ProjectId,
  'status' : ProjectStatus,
  'endDate' : [] | [Timestamp],
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'totalExpenses' : bigint,
  'budgetAllocation' : bigint,
  'updatedAt' : Timestamp,
  'startDate' : Timestamp,
}
export type ProjectStatus = { 'completed' : null } |
  { 'ongoing' : null } |
  { 'planning' : null };
export interface Purchase {
  'date' : Timestamp,
  'description' : string,
  'purchaseId' : PurchaseId,
  'amount' : bigint,
  'supplierId' : SupplierId,
  'transactionId' : TransactionId,
}
export type PurchaseId = bigint;
export type Role = { 'chairperson' : null } |
  { 'treasurer' : null };
export interface SubscriptionPublic {
  'status' : SubscriptionStatus,
  'subscriptionEndDate' : [] | [Timestamp],
  'userId' : UserId,
  'amountPaid' : bigint,
  'subscriptionStartDate' : [] | [Timestamp],
  'trialStartDate' : [] | [Timestamp],
  'planName' : string,
}
export type SubscriptionStatus = { 'trial' : null } |
  { 'active' : null } |
  { 'expired' : null };
export type SupplierId = bigint;
export interface SupplierPublic {
  'id' : SupplierId,
  'tin' : string,
  'isVatRegistered' : boolean,
  'name' : string,
  'createdAt' : Timestamp,
  'contactPerson' : string,
  'address' : string,
  'phone' : string,
}
export interface SupportingDocPublic {
  'isSubmitted' : boolean,
  'linkedReportId' : CoaReportId,
  'docType' : string,
}
export type Timestamp = bigint;
export interface TransactionFilter {
  'paymentMethod' : [] | [PaymentMethod],
  'toDate' : [] | [Timestamp],
  'projectId' : [] | [ProjectId],
  'fromDate' : [] | [Timestamp],
  'txType' : [] | [TransactionType],
}
export type TransactionId = bigint;
export interface TransactionPublic {
  'id' : TransactionId,
  'paymentMethod' : PaymentMethod,
  'userId' : UserId,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'projectId' : [] | [ProjectId],
  'checkDetails' : [] | [CheckDetailsPublic],
  'txType' : TransactionType,
  'receiptId' : [] | [DocumentId],
  'amount' : bigint,
  'supplierId' : [] | [SupplierId],
}
export type TransactionType = { 'projectExpenses' : null } |
  { 'expenses' : null } |
  { 'cashAdvance' : null } |
  { 'reimbursement' : null } |
  { 'income' : null };
export type UserId = bigint;
export interface UserPublic {
  'id' : UserId,
  'lastActivity' : Timestamp,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : Role,
  'isActive' : boolean,
  'email' : string,
}
export interface _SERVICE {
  'activateSubscription' : ActorMethod<
    [UserId, Timestamp, bigint],
    [] | [SubscriptionPublic]
  >,
  'addAllocation' : ActorMethod<[string, bigint], AllocationPublic>,
  'addAuditLog' : ActorMethod<[UserId, string, AuditAction, string], AuditLog>,
  'addCoaReport' : ActorMethod<
    [CoaReportType, bigint, [] | [bigint], [] | [Timestamp]],
    CoaReportPublic
  >,
  'addDocument' : ActorMethod<
    [string, string, UserId, [] | [TransactionId], [] | [ProjectId], string],
    Document
  >,
  'addNotification' : ActorMethod<
    [UserId, NotificationType, string, string],
    NotificationPublic
  >,
  'addProject' : ActorMethod<[AddProjectInput], ProjectPublic>,
  'addPurchase' : ActorMethod<
    [SupplierId, TransactionId, bigint, Timestamp, string],
    Purchase
  >,
  'addSupplier' : ActorMethod<
    [string, string, boolean, string, string, string],
    SupplierPublic
  >,
  'addTransaction' : ActorMethod<
    [AddTransactionInput, UserId],
    TransactionPublic
  >,
  'checkSubscriptionStatus' : ActorMethod<[UserId], [] | [SubscriptionStatus]>,
  'createSubscription' : ActorMethod<
    [UserId, string, boolean],
    SubscriptionPublic
  >,
  'createUser' : ActorMethod<[string, string, string, Role], CreateUserResult>,
  'deleteAllocation' : ActorMethod<[AllocationId], boolean>,
  'deleteDocument' : ActorMethod<[DocumentId], boolean>,
  'deleteProject' : ActorMethod<[ProjectId], boolean>,
  'deleteSupplier' : ActorMethod<[SupplierId], boolean>,
  'deleteTransaction' : ActorMethod<[TransactionId], boolean>,
  'dismissNotification' : ActorMethod<[NotificationId], boolean>,
  'expireSubscription' : ActorMethod<[UserId], [] | [SubscriptionPublic]>,
  'getActiveProjectsCount' : ActorMethod<[], bigint>,
  'getAllocations' : ActorMethod<[], Array<AllocationPublic>>,
  'getAuditLogs' : ActorMethod<[[] | [AuditFilter]], Array<AuditLog>>,
  'getBudget' : ActorMethod<[], [] | [Budget]>,
  'getCoaReports' : ActorMethod<[], Array<CoaReportPublic>>,
  'getDashboardSummary' : ActorMethod<
    [],
    {
      'activeProjectsCount' : bigint,
      'totalIncome' : bigint,
      'totalExpenses' : bigint,
      'totalBudget' : [] | [bigint],
      'remainingBalance' : [] | [bigint],
    }
  >,
  'getDocumentById' : ActorMethod<[DocumentId], [] | [Document]>,
  'getDocuments' : ActorMethod<[], Array<Document>>,
  'getDocumentsByProject' : ActorMethod<[ProjectId], Array<Document>>,
  'getDocumentsByTransaction' : ActorMethod<[TransactionId], Array<Document>>,
  'getNotifications' : ActorMethod<[UserId], Array<NotificationPublic>>,
  'getOverdueReports' : ActorMethod<[], Array<CoaReportPublic>>,
  'getProjectById' : ActorMethod<[ProjectId], [] | [ProjectPublic]>,
  'getProjects' : ActorMethod<[], Array<ProjectPublic>>,
  'getPurchasesBySupplier' : ActorMethod<[SupplierId], Array<Purchase>>,
  'getRecentLogs' : ActorMethod<[bigint], Array<AuditLog>>,
  'getRemainingBalance' : ActorMethod<[], [] | [bigint]>,
  'getSubscription' : ActorMethod<[UserId], [] | [SubscriptionPublic]>,
  'getSupplierById' : ActorMethod<[SupplierId], [] | [SupplierPublic]>,
  'getSuppliers' : ActorMethod<[], Array<SupplierPublic>>,
  'getSupportingDocs' : ActorMethod<[CoaReportId], Array<SupportingDocPublic>>,
  'getTotalExpenses' : ActorMethod<[], bigint>,
  'getTotalIncome' : ActorMethod<[], bigint>,
  'getTransactionById' : ActorMethod<[TransactionId], [] | [TransactionPublic]>,
  'getTransactions' : ActorMethod<
    [[] | [TransactionFilter]],
    Array<TransactionPublic>
  >,
  'getUnreadCount' : ActorMethod<[UserId], bigint>,
  'getUserById' : ActorMethod<[UserId], [] | [UserPublic]>,
  'getUserByToken' : ActorMethod<[string], [] | [UserPublic]>,
  'login' : ActorMethod<[string, string], LoginResult>,
  'logout' : ActorMethod<[string], boolean>,
  'markAsRead' : ActorMethod<[NotificationId], boolean>,
  'setBudget' : ActorMethod<[bigint, bigint], Budget>,
  'submitSupportingDoc' : ActorMethod<[CoaReportId, string], boolean>,
  'updateAllocation' : ActorMethod<
    [AllocationId, string, bigint],
    [] | [AllocationPublic]
  >,
  'updateCoaReport' : ActorMethod<
    [CoaReportId, CoaReportStatus, string],
    [] | [CoaReportPublic]
  >,
  'updateProject' : ActorMethod<
    [ProjectId, AddProjectInput],
    [] | [ProjectPublic]
  >,
  'updateProjectStatus' : ActorMethod<
    [ProjectId, ProjectStatus],
    [] | [ProjectPublic]
  >,
  'updateSubscription' : ActorMethod<
    [UserId, SubscriptionStatus, [] | [Timestamp], bigint],
    [] | [SubscriptionPublic]
  >,
  'updateSupplier' : ActorMethod<
    [SupplierId, string, string, boolean, string, string, string],
    [] | [SupplierPublic]
  >,
  'updateTransaction' : ActorMethod<
    [TransactionId, AddTransactionInput],
    [] | [TransactionPublic]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];