/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Budget {
    fiscalYear: bigint;
    totalBudget: bigint;
}
export interface TransactionPublic {
    id: TransactionId;
    paymentMethod: PaymentMethod;
    userId: UserId;
    date: Timestamp;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    projectId?: ProjectId;
    checkDetails?: CheckDetailsPublic;
    txType: TransactionType;
    receiptId?: DocumentId;
    amount: bigint;
    supplierId?: SupplierId;
}
export type Timestamp = bigint;
export interface UserPublic {
    id: UserId;
    lastActivity: Timestamp;
    name: string;
    createdAt: Timestamp;
    role: Role;
    isActive: boolean;
    email: string;
}
export interface AuditLog {
    id: AuditLogId;
    action: AuditAction;
    userEmail: string;
    userId: UserId;
    description: string;
    timestamp: Timestamp;
}
export interface Document {
    id: DocumentId;
    linkedTransactionId?: TransactionId;
    linkedProjectId?: ProjectId;
    fileName: string;
    fileType: string;
    storageKey: string;
    uploadedAt: Timestamp;
    uploadedBy: UserId;
}
export interface CoaReportPublic {
    id: CoaReportId;
    status: CoaReportStatus;
    fiscalYear: bigint;
    quarter?: bigint;
    createdAt: Timestamp;
    submittedAt?: Timestamp;
    deadline?: Timestamp;
    reportType: CoaReportType;
    notes: string;
}
export type AuditLogId = bigint;
export interface AuditFilter {
    action?: AuditAction;
    userId?: UserId;
    toDate?: Timestamp;
    fromDate?: Timestamp;
}
export type CreateUserResult = {
    __kind__: "ok";
    ok: UserPublic;
} | {
    __kind__: "err";
    err: string;
};
export type TransactionId = bigint;
export interface SupplierPublic {
    id: SupplierId;
    tin: string;
    isVatRegistered: boolean;
    name: string;
    createdAt: Timestamp;
    contactPerson: string;
    address: string;
    phone: string;
}
export interface ProjectPublic {
    id: ProjectId;
    status: ProjectStatus;
    endDate?: Timestamp;
    name: string;
    createdAt: Timestamp;
    description: string;
    totalExpenses: bigint;
    budgetAllocation: bigint;
    updatedAt: Timestamp;
    startDate: Timestamp;
}
export type AllocationId = bigint;
export type DocumentId = bigint;
export type SupplierId = bigint;
export interface AddTransactionInput {
    paymentMethod: PaymentMethod;
    date: Timestamp;
    description: string;
    projectId?: ProjectId;
    checkDetails?: CheckDetailsPublic;
    txType: TransactionType;
    receiptId?: DocumentId;
    amount: bigint;
    supplierId?: SupplierId;
}
export interface Purchase {
    date: Timestamp;
    description: string;
    purchaseId: PurchaseId;
    amount: bigint;
    supplierId: SupplierId;
    transactionId: TransactionId;
}
export interface CheckDetailsPublic {
    status: CheckStatus;
    bankName: string;
    checkNumber?: string;
    checkDate: Timestamp;
    payee: string;
    purpose: string;
}
export interface NotificationPublic {
    id: NotificationId;
    title: string;
    notifType: NotificationType;
    userId: UserId;
    createdAt: Timestamp;
    isRead: boolean;
    message: string;
}
export interface SubscriptionPublic {
    status: SubscriptionStatus;
    subscriptionEndDate?: Timestamp;
    userId: UserId;
    amountPaid: bigint;
    subscriptionStartDate?: Timestamp;
    trialStartDate?: Timestamp;
    planName: string;
}
export interface TransactionFilter {
    paymentMethod?: PaymentMethod;
    toDate?: Timestamp;
    projectId?: ProjectId;
    fromDate?: Timestamp;
    txType?: TransactionType;
}
export interface AddProjectInput {
    endDate?: Timestamp;
    name: string;
    description: string;
    budgetAllocation: bigint;
    startDate: Timestamp;
}
export interface SupportingDocPublic {
    isSubmitted: boolean;
    linkedReportId: CoaReportId;
    docType: string;
}
export type UserId = bigint;
export type NotificationId = bigint;
export type PurchaseId = bigint;
export type ProjectId = bigint;
export type CoaReportId = bigint;
export type LoginResult = {
    __kind__: "ok";
    ok: {
        token: string;
        user: UserPublic;
    };
} | {
    __kind__: "err";
    err: string;
};
export interface AllocationPublic {
    id: AllocationId;
    name: string;
    allocatedAmount: bigint;
    spentAmount: bigint;
}
export enum AuditAction {
    generateReport = "generateReport",
    deleteTransaction = "deleteTransaction",
    other = "other",
    editTransaction = "editTransaction",
    login = "login",
    addTransaction = "addTransaction"
}
export enum CheckStatus {
    cancelled = "cancelled",
    issued = "issued",
    pendingIssuance = "pendingIssuance",
    cleared = "cleared"
}
export enum CoaReportStatus {
    pendingReview = "pendingReview",
    submitted = "submitted",
    needsRevision = "needsRevision",
    approved = "approved",
    draft = "draft"
}
export enum CoaReportType {
    notesToFS = "notesToFS",
    inventoryReport = "inventoryReport",
    asrp = "asrp",
    qsrp = "qsrp",
    raaf = "raaf",
    budgetVsActual = "budgetVsActual"
}
export enum NotificationType {
    budgetAlert = "budgetAlert",
    coaDeadline = "coaDeadline",
    missingReceipt = "missingReceipt",
    pendingApproval = "pendingApproval",
    subscriptionReminder = "subscriptionReminder"
}
export enum PaymentMethod {
    cash = "cash",
    check = "check",
    bankTransfer = "bankTransfer",
    gcash = "gcash"
}
export enum ProjectStatus {
    completed = "completed",
    ongoing = "ongoing",
    planning = "planning"
}
export enum Role {
    chairperson = "chairperson",
    treasurer = "treasurer"
}
export enum SubscriptionStatus {
    trial = "trial",
    active = "active",
    expired = "expired"
}
export enum TransactionType {
    projectExpenses = "projectExpenses",
    expenses = "expenses",
    cashAdvance = "cashAdvance",
    reimbursement = "reimbursement",
    income = "income"
}
export interface backendInterface {
    activateSubscription(userId: UserId, endDate: Timestamp, amountPaid: bigint): Promise<SubscriptionPublic | null>;
    addAllocation(name: string, amount: bigint): Promise<AllocationPublic>;
    addAuditLog(userId: UserId, userEmail: string, action: AuditAction, description: string): Promise<AuditLog>;
    addCoaReport(reportType: CoaReportType, fiscalYear: bigint, quarter: bigint | null, deadline: Timestamp | null): Promise<CoaReportPublic>;
    addDocument(fileName: string, fileType: string, uploadedBy: UserId, linkedTransactionId: TransactionId | null, linkedProjectId: ProjectId | null, storageKey: string): Promise<Document>;
    addNotification(userId: UserId, notifType: NotificationType, title: string, message: string): Promise<NotificationPublic>;
    addProject(input: AddProjectInput): Promise<ProjectPublic>;
    addPurchase(supplierId: SupplierId, transactionId: TransactionId, amount: bigint, date: Timestamp, description: string): Promise<Purchase>;
    addSupplier(name: string, tin: string, isVatRegistered: boolean, contactPerson: string, phone: string, address: string): Promise<SupplierPublic>;
    addTransaction(input: AddTransactionInput, userId: UserId): Promise<TransactionPublic>;
    checkSubscriptionStatus(userId: UserId): Promise<SubscriptionStatus | null>;
    createSubscription(userId: UserId, planName: string, startAsTrial: boolean): Promise<SubscriptionPublic>;
    createUser(email: string, passwordHash: string, name: string, role: Role): Promise<CreateUserResult>;
    deleteAllocation(id: AllocationId): Promise<boolean>;
    deleteDocument(id: DocumentId): Promise<boolean>;
    deleteProject(id: ProjectId): Promise<boolean>;
    deleteSupplier(id: SupplierId): Promise<boolean>;
    deleteTransaction(id: TransactionId): Promise<boolean>;
    dismissNotification(id: NotificationId): Promise<boolean>;
    expireSubscription(userId: UserId): Promise<SubscriptionPublic | null>;
    getActiveProjectsCount(): Promise<bigint>;
    getAllocations(): Promise<Array<AllocationPublic>>;
    getAuditLogs(filter: AuditFilter | null): Promise<Array<AuditLog>>;
    getBudget(): Promise<Budget | null>;
    getCoaReports(): Promise<Array<CoaReportPublic>>;
    getDashboardSummary(): Promise<{
        activeProjectsCount: bigint;
        totalIncome: bigint;
        totalExpenses: bigint;
        totalBudget?: bigint;
        remainingBalance?: bigint;
    }>;
    getDocumentById(id: DocumentId): Promise<Document | null>;
    getDocuments(): Promise<Array<Document>>;
    getDocumentsByProject(projectId: ProjectId): Promise<Array<Document>>;
    getDocumentsByTransaction(transactionId: TransactionId): Promise<Array<Document>>;
    getNotifications(userId: UserId): Promise<Array<NotificationPublic>>;
    getOverdueReports(): Promise<Array<CoaReportPublic>>;
    getProjectById(id: ProjectId): Promise<ProjectPublic | null>;
    getProjects(): Promise<Array<ProjectPublic>>;
    getPurchasesBySupplier(supplierId: SupplierId): Promise<Array<Purchase>>;
    getRecentLogs(limit: bigint): Promise<Array<AuditLog>>;
    getRemainingBalance(): Promise<bigint | null>;
    getSubscription(userId: UserId): Promise<SubscriptionPublic | null>;
    getSupplierById(id: SupplierId): Promise<SupplierPublic | null>;
    getSuppliers(): Promise<Array<SupplierPublic>>;
    getSupportingDocs(reportId: CoaReportId): Promise<Array<SupportingDocPublic>>;
    getTotalExpenses(): Promise<bigint>;
    getTotalIncome(): Promise<bigint>;
    getTransactionById(id: TransactionId): Promise<TransactionPublic | null>;
    getTransactions(filter: TransactionFilter | null): Promise<Array<TransactionPublic>>;
    getUnreadCount(userId: UserId): Promise<bigint>;
    getUserById(id: UserId): Promise<UserPublic | null>;
    getUserByToken(token: string): Promise<UserPublic | null>;
    login(email: string, passwordHash: string): Promise<LoginResult>;
    logout(token: string): Promise<boolean>;
    markAsRead(id: NotificationId): Promise<boolean>;
    setBudget(totalBudget: bigint, fiscalYear: bigint): Promise<Budget>;
    submitSupportingDoc(reportId: CoaReportId, docType: string): Promise<boolean>;
    updateAllocation(id: AllocationId, name: string, amount: bigint): Promise<AllocationPublic | null>;
    updateCoaReport(id: CoaReportId, status: CoaReportStatus, notes: string): Promise<CoaReportPublic | null>;
    updateProject(id: ProjectId, input: AddProjectInput): Promise<ProjectPublic | null>;
    updateProjectStatus(id: ProjectId, status: ProjectStatus): Promise<ProjectPublic | null>;
    updateSubscription(userId: UserId, status: SubscriptionStatus, subscriptionEndDate: Timestamp | null, amountPaid: bigint): Promise<SubscriptionPublic | null>;
    updateSupplier(id: SupplierId, name: string, tin: string, isVatRegistered: boolean, contactPerson: string, phone: string, address: string): Promise<SupplierPublic | null>;
    updateTransaction(id: TransactionId, input: AddTransactionInput): Promise<TransactionPublic | null>;
}
import type { AddProjectInput as _AddProjectInput, AddTransactionInput as _AddTransactionInput, AllocationPublic as _AllocationPublic, AuditAction as _AuditAction, AuditFilter as _AuditFilter, AuditLog as _AuditLog, AuditLogId as _AuditLogId, Budget as _Budget, CheckDetailsPublic as _CheckDetailsPublic, CheckStatus as _CheckStatus, CoaReportId as _CoaReportId, CoaReportPublic as _CoaReportPublic, CoaReportStatus as _CoaReportStatus, CoaReportType as _CoaReportType, CreateUserResult as _CreateUserResult, Document as _Document, DocumentId as _DocumentId, LoginResult as _LoginResult, NotificationId as _NotificationId, NotificationPublic as _NotificationPublic, NotificationType as _NotificationType, PaymentMethod as _PaymentMethod, ProjectId as _ProjectId, ProjectPublic as _ProjectPublic, ProjectStatus as _ProjectStatus, Role as _Role, SubscriptionPublic as _SubscriptionPublic, SubscriptionStatus as _SubscriptionStatus, SupplierId as _SupplierId, SupplierPublic as _SupplierPublic, Timestamp as _Timestamp, TransactionFilter as _TransactionFilter, TransactionId as _TransactionId, TransactionPublic as _TransactionPublic, TransactionType as _TransactionType, UserId as _UserId, UserPublic as _UserPublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async activateSubscription(arg0: UserId, arg1: Timestamp, arg2: bigint): Promise<SubscriptionPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.activateSubscription(arg0, arg1, arg2);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateSubscription(arg0, arg1, arg2);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async addAllocation(arg0: string, arg1: bigint): Promise<AllocationPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.addAllocation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAllocation(arg0, arg1);
            return result;
        }
    }
    async addAuditLog(arg0: UserId, arg1: string, arg2: AuditAction, arg3: string): Promise<AuditLog> {
        if (this.processError) {
            try {
                const result = await this.actor.addAuditLog(arg0, arg1, to_candid_AuditAction_n7(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_AuditLog_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAuditLog(arg0, arg1, to_candid_AuditAction_n7(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_AuditLog_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async addCoaReport(arg0: CoaReportType, arg1: bigint, arg2: bigint | null, arg3: Timestamp | null): Promise<CoaReportPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.addCoaReport(to_candid_CoaReportType_n13(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg3));
                return from_candid_CoaReportPublic_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCoaReport(to_candid_CoaReportType_n13(this._uploadFile, this._downloadFile, arg0), arg1, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg3));
            return from_candid_CoaReportPublic_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async addDocument(arg0: string, arg1: string, arg2: UserId, arg3: TransactionId | null, arg4: ProjectId | null, arg5: string): Promise<Document> {
        if (this.processError) {
            try {
                const result = await this.actor.addDocument(arg0, arg1, arg2, to_candid_opt_n24(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_Document_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDocument(arg0, arg1, arg2, to_candid_opt_n24(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_Document_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async addNotification(arg0: UserId, arg1: NotificationType, arg2: string, arg3: string): Promise<NotificationPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.addNotification(arg0, to_candid_NotificationType_n30(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return from_candid_NotificationPublic_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNotification(arg0, to_candid_NotificationType_n30(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return from_candid_NotificationPublic_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async addProject(arg0: AddProjectInput): Promise<ProjectPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.addProject(to_candid_AddProjectInput_n36(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ProjectPublic_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProject(to_candid_AddProjectInput_n36(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ProjectPublic_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async addPurchase(arg0: SupplierId, arg1: TransactionId, arg2: bigint, arg3: Timestamp, arg4: string): Promise<Purchase> {
        if (this.processError) {
            try {
                const result = await this.actor.addPurchase(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPurchase(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addSupplier(arg0: string, arg1: string, arg2: boolean, arg3: string, arg4: string, arg5: string): Promise<SupplierPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.addSupplier(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSupplier(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addTransaction(arg0: AddTransactionInput, arg1: UserId): Promise<TransactionPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransaction(to_candid_AddTransactionInput_n42(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_TransactionPublic_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransaction(to_candid_AddTransactionInput_n42(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_TransactionPublic_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkSubscriptionStatus(arg0: UserId): Promise<SubscriptionStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.checkSubscriptionStatus(arg0);
                return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkSubscriptionStatus(arg0);
            return from_candid_opt_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSubscription(arg0: UserId, arg1: string, arg2: boolean): Promise<SubscriptionPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubscription(arg0, arg1, arg2);
                return from_candid_SubscriptionPublic_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubscription(arg0, arg1, arg2);
            return from_candid_SubscriptionPublic_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async createUser(arg0: string, arg1: string, arg2: string, arg3: Role): Promise<CreateUserResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1, arg2, to_candid_Role_n67(this._uploadFile, this._downloadFile, arg3));
                return from_candid_CreateUserResult_n69(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1, arg2, to_candid_Role_n67(this._uploadFile, this._downloadFile, arg3));
            return from_candid_CreateUserResult_n69(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAllocation(arg0: AllocationId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllocation(arg0);
            return result;
        }
    }
    async deleteDocument(arg0: DocumentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDocument(arg0);
            return result;
        }
    }
    async deleteProject(arg0: ProjectId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProject(arg0);
            return result;
        }
    }
    async deleteSupplier(arg0: SupplierId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSupplier(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSupplier(arg0);
            return result;
        }
    }
    async deleteTransaction(arg0: TransactionId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransaction(arg0);
            return result;
        }
    }
    async dismissNotification(arg0: NotificationId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.dismissNotification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dismissNotification(arg0);
            return result;
        }
    }
    async expireSubscription(arg0: UserId): Promise<SubscriptionPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.expireSubscription(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.expireSubscription(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveProjectsCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveProjectsCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveProjectsCount();
            return result;
        }
    }
    async getAllocations(): Promise<Array<AllocationPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllocations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllocations();
            return result;
        }
    }
    async getAuditLogs(arg0: AuditFilter | null): Promise<Array<AuditLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLogs(to_candid_opt_n75(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n78(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLogs(to_candid_opt_n75(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n78(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBudget(): Promise<Budget | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBudget();
                return from_candid_opt_n79(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBudget();
            return from_candid_opt_n79(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCoaReports(): Promise<Array<CoaReportPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCoaReports();
                return from_candid_vec_n80(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCoaReports();
            return from_candid_vec_n80(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardSummary(): Promise<{
        activeProjectsCount: bigint;
        totalIncome: bigint;
        totalExpenses: bigint;
        totalBudget?: bigint;
        remainingBalance?: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardSummary();
                return from_candid_record_n81(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardSummary();
            return from_candid_record_n81(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocumentById(arg0: DocumentId): Promise<Document | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentById(arg0);
                return from_candid_opt_n82(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentById(arg0);
            return from_candid_opt_n82(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocuments(): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocuments();
                return from_candid_vec_n83(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocuments();
            return from_candid_vec_n83(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocumentsByProject(arg0: ProjectId): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentsByProject(arg0);
                return from_candid_vec_n83(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentsByProject(arg0);
            return from_candid_vec_n83(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDocumentsByTransaction(arg0: TransactionId): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDocumentsByTransaction(arg0);
                return from_candid_vec_n83(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDocumentsByTransaction(arg0);
            return from_candid_vec_n83(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(arg0: UserId): Promise<Array<NotificationPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications(arg0);
                return from_candid_vec_n84(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications(arg0);
            return from_candid_vec_n84(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOverdueReports(): Promise<Array<CoaReportPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOverdueReports();
                return from_candid_vec_n80(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOverdueReports();
            return from_candid_vec_n80(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjectById(arg0: ProjectId): Promise<ProjectPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjectById(arg0);
                return from_candid_opt_n85(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjectById(arg0);
            return from_candid_opt_n85(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProjects(): Promise<Array<ProjectPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProjects();
                return from_candid_vec_n86(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProjects();
            return from_candid_vec_n86(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPurchasesBySupplier(arg0: SupplierId): Promise<Array<Purchase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPurchasesBySupplier(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPurchasesBySupplier(arg0);
            return result;
        }
    }
    async getRecentLogs(arg0: bigint): Promise<Array<AuditLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentLogs(arg0);
                return from_candid_vec_n78(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentLogs(arg0);
            return from_candid_vec_n78(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRemainingBalance(): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRemainingBalance();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRemainingBalance();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscription(arg0: UserId): Promise<SubscriptionPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscription(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscription(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSupplierById(arg0: SupplierId): Promise<SupplierPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupplierById(arg0);
                return from_candid_opt_n87(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupplierById(arg0);
            return from_candid_opt_n87(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSuppliers(): Promise<Array<SupplierPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSuppliers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSuppliers();
            return result;
        }
    }
    async getSupportingDocs(arg0: CoaReportId): Promise<Array<SupportingDocPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupportingDocs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupportingDocs(arg0);
            return result;
        }
    }
    async getTotalExpenses(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalExpenses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalExpenses();
            return result;
        }
    }
    async getTotalIncome(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalIncome();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalIncome();
            return result;
        }
    }
    async getTransactionById(arg0: TransactionId): Promise<TransactionPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionById(arg0);
                return from_candid_opt_n88(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionById(arg0);
            return from_candid_opt_n88(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactions(arg0: TransactionFilter | null): Promise<Array<TransactionPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactions(to_candid_opt_n89(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n92(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactions(to_candid_opt_n89(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n92(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadCount(arg0: UserId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadCount(arg0);
            return result;
        }
    }
    async getUserById(arg0: UserId): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserById(arg0);
                return from_candid_opt_n93(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserById(arg0);
            return from_candid_opt_n93(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserByToken(arg0: string): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByToken(arg0);
                return from_candid_opt_n93(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByToken(arg0);
            return from_candid_opt_n93(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: string, arg1: string): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_LoginResult_n94(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_LoginResult_n94(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.logout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout(arg0);
            return result;
        }
    }
    async markAsRead(arg0: NotificationId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAsRead(arg0);
            return result;
        }
    }
    async setBudget(arg0: bigint, arg1: bigint): Promise<Budget> {
        if (this.processError) {
            try {
                const result = await this.actor.setBudget(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBudget(arg0, arg1);
            return result;
        }
    }
    async submitSupportingDoc(arg0: CoaReportId, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.submitSupportingDoc(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitSupportingDoc(arg0, arg1);
            return result;
        }
    }
    async updateAllocation(arg0: AllocationId, arg1: string, arg2: bigint): Promise<AllocationPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAllocation(arg0, arg1, arg2);
                return from_candid_opt_n97(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAllocation(arg0, arg1, arg2);
            return from_candid_opt_n97(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCoaReport(arg0: CoaReportId, arg1: CoaReportStatus, arg2: string): Promise<CoaReportPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCoaReport(arg0, to_candid_CoaReportStatus_n98(this._uploadFile, this._downloadFile, arg1), arg2);
                return from_candid_opt_n100(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCoaReport(arg0, to_candid_CoaReportStatus_n98(this._uploadFile, this._downloadFile, arg1), arg2);
            return from_candid_opt_n100(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProject(arg0: ProjectId, arg1: AddProjectInput): Promise<ProjectPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProject(arg0, to_candid_AddProjectInput_n36(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n85(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProject(arg0, to_candid_AddProjectInput_n36(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n85(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProjectStatus(arg0: ProjectId, arg1: ProjectStatus): Promise<ProjectPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProjectStatus(arg0, to_candid_ProjectStatus_n101(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n85(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProjectStatus(arg0, to_candid_ProjectStatus_n101(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n85(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSubscription(arg0: UserId, arg1: SubscriptionStatus, arg2: Timestamp | null, arg3: bigint): Promise<SubscriptionPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubscription(arg0, to_candid_SubscriptionStatus_n103(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg2), arg3);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubscription(arg0, to_candid_SubscriptionStatus_n103(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n16(this._uploadFile, this._downloadFile, arg2), arg3);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSupplier(arg0: SupplierId, arg1: string, arg2: string, arg3: boolean, arg4: string, arg5: string, arg6: string): Promise<SupplierPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSupplier(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return from_candid_opt_n87(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSupplier(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return from_candid_opt_n87(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTransaction(arg0: TransactionId, arg1: AddTransactionInput): Promise<TransactionPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransaction(arg0, to_candid_AddTransactionInput_n42(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n88(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransaction(arg0, to_candid_AddTransactionInput_n42(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n88(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AuditAction_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditAction): AuditAction {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_AuditLog_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditLog): AuditLog {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_CheckDetailsPublic_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CheckDetailsPublic): CheckDetailsPublic {
    return from_candid_record_n58(_uploadFile, _downloadFile, value);
}
function from_candid_CheckStatus_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CheckStatus): CheckStatus {
    return from_candid_variant_n60(_uploadFile, _downloadFile, value);
}
function from_candid_CoaReportPublic_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoaReportPublic): CoaReportPublic {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_CoaReportStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoaReportStatus): CoaReportStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_CoaReportType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoaReportType): CoaReportType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_CreateUserResult_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreateUserResult): CreateUserResult {
    return from_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function from_candid_Document_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Document): Document {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_LoginResult_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginResult): LoginResult {
    return from_candid_variant_n95(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationPublic_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationPublic): NotificationPublic {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectPublic_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectPublic): ProjectPublic {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_ProjectStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProjectStatus): ProjectStatus {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n74(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionPublic_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionPublic): SubscriptionPublic {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionPublic_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionPublic): TransactionPublic {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function from_candid_UserPublic_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPublic): UserPublic {
    return from_candid_record_n72(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubscriptionPublic]): SubscriptionPublic | null {
    return value.length === 0 ? null : from_candid_SubscriptionPublic_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n100(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CoaReportPublic]): CoaReportPublic | null {
    return value.length === 0 ? null : from_candid_CoaReportPublic_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TransactionId]): TransactionId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProjectId]): ProjectId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CheckDetailsPublic]): CheckDetailsPublic | null {
    return value.length === 0 ? null : from_candid_CheckDetailsPublic_n57(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DocumentId]): DocumentId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SupplierId]): SupplierId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SubscriptionStatus]): SubscriptionStatus | null {
    return value.length === 0 ? null : from_candid_SubscriptionStatus_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Budget]): Budget | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Document]): Document | null {
    return value.length === 0 ? null : from_candid_Document_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProjectPublic]): ProjectPublic | null {
    return value.length === 0 ? null : from_candid_ProjectPublic_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SupplierPublic]): SupplierPublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TransactionPublic]): TransactionPublic | null {
    return value.length === 0 ? null : from_candid_TransactionPublic_n52(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPublic]): UserPublic | null {
    return value.length === 0 ? null : from_candid_UserPublic_n71(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n97(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AllocationPublic]): AllocationPublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AuditLogId;
    action: _AuditAction;
    userEmail: string;
    userId: _UserId;
    description: string;
    timestamp: _Timestamp;
}): {
    id: AuditLogId;
    action: AuditAction;
    userEmail: string;
    userId: UserId;
    description: string;
    timestamp: Timestamp;
} {
    return {
        id: value.id,
        action: from_candid_AuditAction_n11(_uploadFile, _downloadFile, value.action),
        userEmail: value.userEmail,
        userId: value.userId,
        description: value.description,
        timestamp: value.timestamp
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CoaReportId;
    status: _CoaReportStatus;
    fiscalYear: bigint;
    quarter: [] | [bigint];
    createdAt: _Timestamp;
    submittedAt: [] | [_Timestamp];
    deadline: [] | [_Timestamp];
    reportType: _CoaReportType;
    notes: string;
}): {
    id: CoaReportId;
    status: CoaReportStatus;
    fiscalYear: bigint;
    quarter?: bigint;
    createdAt: Timestamp;
    submittedAt?: Timestamp;
    deadline?: Timestamp;
    reportType: CoaReportType;
    notes: string;
} {
    return {
        id: value.id,
        status: from_candid_CoaReportStatus_n19(_uploadFile, _downloadFile, value.status),
        fiscalYear: value.fiscalYear,
        quarter: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.quarter)),
        createdAt: value.createdAt,
        submittedAt: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.submittedAt)),
        deadline: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.deadline)),
        reportType: from_candid_CoaReportType_n22(_uploadFile, _downloadFile, value.reportType),
        notes: value.notes
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DocumentId;
    linkedTransactionId: [] | [_TransactionId];
    linkedProjectId: [] | [_ProjectId];
    fileName: string;
    fileType: string;
    storageKey: string;
    uploadedAt: _Timestamp;
    uploadedBy: _UserId;
}): {
    id: DocumentId;
    linkedTransactionId?: TransactionId;
    linkedProjectId?: ProjectId;
    fileName: string;
    fileType: string;
    storageKey: string;
    uploadedAt: Timestamp;
    uploadedBy: UserId;
} {
    return {
        id: value.id,
        linkedTransactionId: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.linkedTransactionId)),
        linkedProjectId: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.linkedProjectId)),
        fileName: value.fileName,
        fileType: value.fileType,
        storageKey: value.storageKey,
        uploadedAt: value.uploadedAt,
        uploadedBy: value.uploadedBy
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _SubscriptionStatus;
    subscriptionEndDate: [] | [_Timestamp];
    userId: _UserId;
    amountPaid: bigint;
    subscriptionStartDate: [] | [_Timestamp];
    trialStartDate: [] | [_Timestamp];
    planName: string;
}): {
    status: SubscriptionStatus;
    subscriptionEndDate?: Timestamp;
    userId: UserId;
    amountPaid: bigint;
    subscriptionStartDate?: Timestamp;
    trialStartDate?: Timestamp;
    planName: string;
} {
    return {
        status: from_candid_SubscriptionStatus_n4(_uploadFile, _downloadFile, value.status),
        subscriptionEndDate: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.subscriptionEndDate)),
        userId: value.userId,
        amountPaid: value.amountPaid,
        subscriptionStartDate: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.subscriptionStartDate)),
        trialStartDate: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.trialStartDate)),
        planName: value.planName
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NotificationId;
    title: string;
    notifType: _NotificationType;
    userId: _UserId;
    createdAt: _Timestamp;
    isRead: boolean;
    message: string;
}): {
    id: NotificationId;
    title: string;
    notifType: NotificationType;
    userId: UserId;
    createdAt: Timestamp;
    isRead: boolean;
    message: string;
} {
    return {
        id: value.id,
        title: value.title,
        notifType: from_candid_NotificationType_n34(_uploadFile, _downloadFile, value.notifType),
        userId: value.userId,
        createdAt: value.createdAt,
        isRead: value.isRead,
        message: value.message
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProjectId;
    status: _ProjectStatus;
    endDate: [] | [_Timestamp];
    name: string;
    createdAt: _Timestamp;
    description: string;
    totalExpenses: bigint;
    budgetAllocation: bigint;
    updatedAt: _Timestamp;
    startDate: _Timestamp;
}): {
    id: ProjectId;
    status: ProjectStatus;
    endDate?: Timestamp;
    name: string;
    createdAt: Timestamp;
    description: string;
    totalExpenses: bigint;
    budgetAllocation: bigint;
    updatedAt: Timestamp;
    startDate: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_ProjectStatus_n40(_uploadFile, _downloadFile, value.status),
        endDate: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.endDate)),
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        totalExpenses: value.totalExpenses,
        budgetAllocation: value.budgetAllocation,
        updatedAt: value.updatedAt,
        startDate: value.startDate
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TransactionId;
    paymentMethod: _PaymentMethod;
    userId: _UserId;
    date: _Timestamp;
    createdAt: _Timestamp;
    description: string;
    updatedAt: _Timestamp;
    projectId: [] | [_ProjectId];
    checkDetails: [] | [_CheckDetailsPublic];
    txType: _TransactionType;
    receiptId: [] | [_DocumentId];
    amount: bigint;
    supplierId: [] | [_SupplierId];
}): {
    id: TransactionId;
    paymentMethod: PaymentMethod;
    userId: UserId;
    date: Timestamp;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    projectId?: ProjectId;
    checkDetails?: CheckDetailsPublic;
    txType: TransactionType;
    receiptId?: DocumentId;
    amount: bigint;
    supplierId?: SupplierId;
} {
    return {
        id: value.id,
        paymentMethod: from_candid_PaymentMethod_n54(_uploadFile, _downloadFile, value.paymentMethod),
        userId: value.userId,
        date: value.date,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        projectId: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.projectId)),
        checkDetails: record_opt_to_undefined(from_candid_opt_n56(_uploadFile, _downloadFile, value.checkDetails)),
        txType: from_candid_TransactionType_n62(_uploadFile, _downloadFile, value.txType),
        receiptId: record_opt_to_undefined(from_candid_opt_n64(_uploadFile, _downloadFile, value.receiptId)),
        amount: value.amount,
        supplierId: record_opt_to_undefined(from_candid_opt_n65(_uploadFile, _downloadFile, value.supplierId))
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _CheckStatus;
    bankName: string;
    checkNumber: [] | [string];
    checkDate: _Timestamp;
    payee: string;
    purpose: string;
}): {
    status: CheckStatus;
    bankName: string;
    checkNumber?: string;
    checkDate: Timestamp;
    payee: string;
    purpose: string;
} {
    return {
        status: from_candid_CheckStatus_n59(_uploadFile, _downloadFile, value.status),
        bankName: value.bankName,
        checkNumber: record_opt_to_undefined(from_candid_opt_n61(_uploadFile, _downloadFile, value.checkNumber)),
        checkDate: value.checkDate,
        payee: value.payee,
        purpose: value.purpose
    };
}
function from_candid_record_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    lastActivity: _Timestamp;
    name: string;
    createdAt: _Timestamp;
    role: _Role;
    isActive: boolean;
    email: string;
}): {
    id: UserId;
    lastActivity: Timestamp;
    name: string;
    createdAt: Timestamp;
    role: Role;
    isActive: boolean;
    email: string;
} {
    return {
        id: value.id,
        lastActivity: value.lastActivity,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_Role_n73(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive,
        email: value.email
    };
}
function from_candid_record_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    activeProjectsCount: bigint;
    totalIncome: bigint;
    totalExpenses: bigint;
    totalBudget: [] | [bigint];
    remainingBalance: [] | [bigint];
}): {
    activeProjectsCount: bigint;
    totalIncome: bigint;
    totalExpenses: bigint;
    totalBudget?: bigint;
    remainingBalance?: bigint;
} {
    return {
        activeProjectsCount: value.activeProjectsCount,
        totalIncome: value.totalIncome,
        totalExpenses: value.totalExpenses,
        totalBudget: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.totalBudget)),
        remainingBalance: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.remainingBalance))
    };
}
function from_candid_record_n96(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    token: string;
    user: _UserPublic;
}): {
    token: string;
    user: UserPublic;
} {
    return {
        token: value.token,
        user: from_candid_UserPublic_n71(_uploadFile, _downloadFile, value.user)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    generateReport: null;
} | {
    deleteTransaction: null;
} | {
    other: null;
} | {
    editTransaction: null;
} | {
    login: null;
} | {
    addTransaction: null;
}): AuditAction {
    return "generateReport" in value ? AuditAction.generateReport : "deleteTransaction" in value ? AuditAction.deleteTransaction : "other" in value ? AuditAction.other : "editTransaction" in value ? AuditAction.editTransaction : "login" in value ? AuditAction.login : "addTransaction" in value ? AuditAction.addTransaction : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pendingReview: null;
} | {
    submitted: null;
} | {
    needsRevision: null;
} | {
    approved: null;
} | {
    draft: null;
}): CoaReportStatus {
    return "pendingReview" in value ? CoaReportStatus.pendingReview : "submitted" in value ? CoaReportStatus.submitted : "needsRevision" in value ? CoaReportStatus.needsRevision : "approved" in value ? CoaReportStatus.approved : "draft" in value ? CoaReportStatus.draft : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notesToFS: null;
} | {
    inventoryReport: null;
} | {
    asrp: null;
} | {
    qsrp: null;
} | {
    raaf: null;
} | {
    budgetVsActual: null;
}): CoaReportType {
    return "notesToFS" in value ? CoaReportType.notesToFS : "inventoryReport" in value ? CoaReportType.inventoryReport : "asrp" in value ? CoaReportType.asrp : "qsrp" in value ? CoaReportType.qsrp : "raaf" in value ? CoaReportType.raaf : "budgetVsActual" in value ? CoaReportType.budgetVsActual : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    budgetAlert: null;
} | {
    coaDeadline: null;
} | {
    missingReceipt: null;
} | {
    pendingApproval: null;
} | {
    subscriptionReminder: null;
}): NotificationType {
    return "budgetAlert" in value ? NotificationType.budgetAlert : "coaDeadline" in value ? NotificationType.coaDeadline : "missingReceipt" in value ? NotificationType.missingReceipt : "pendingApproval" in value ? NotificationType.pendingApproval : "subscriptionReminder" in value ? NotificationType.subscriptionReminder : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: null;
} | {
    ongoing: null;
} | {
    planning: null;
}): ProjectStatus {
    return "completed" in value ? ProjectStatus.completed : "ongoing" in value ? ProjectStatus.ongoing : "planning" in value ? ProjectStatus.planning : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trial: null;
} | {
    active: null;
} | {
    expired: null;
}): SubscriptionStatus {
    return "trial" in value ? SubscriptionStatus.trial : "active" in value ? SubscriptionStatus.active : "expired" in value ? SubscriptionStatus.expired : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cash: null;
} | {
    check: null;
} | {
    bankTransfer: null;
} | {
    gcash: null;
}): PaymentMethod {
    return "cash" in value ? PaymentMethod.cash : "check" in value ? PaymentMethod.check : "bankTransfer" in value ? PaymentMethod.bankTransfer : "gcash" in value ? PaymentMethod.gcash : value;
}
function from_candid_variant_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    issued: null;
} | {
    pendingIssuance: null;
} | {
    cleared: null;
}): CheckStatus {
    return "cancelled" in value ? CheckStatus.cancelled : "issued" in value ? CheckStatus.issued : "pendingIssuance" in value ? CheckStatus.pendingIssuance : "cleared" in value ? CheckStatus.cleared : value;
}
function from_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    projectExpenses: null;
} | {
    expenses: null;
} | {
    cashAdvance: null;
} | {
    reimbursement: null;
} | {
    income: null;
}): TransactionType {
    return "projectExpenses" in value ? TransactionType.projectExpenses : "expenses" in value ? TransactionType.expenses : "cashAdvance" in value ? TransactionType.cashAdvance : "reimbursement" in value ? TransactionType.reimbursement : "income" in value ? TransactionType.income : value;
}
function from_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserPublic_n71(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    chairperson: null;
} | {
    treasurer: null;
}): Role {
    return "chairperson" in value ? Role.chairperson : "treasurer" in value ? Role.treasurer : value;
}
function from_candid_variant_n95(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        token: string;
        user: _UserPublic;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        token: string;
        user: UserPublic;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_record_n96(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AuditLog>): Array<AuditLog> {
    return value.map((x)=>from_candid_AuditLog_n9(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CoaReportPublic>): Array<CoaReportPublic> {
    return value.map((x)=>from_candid_CoaReportPublic_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Document>): Array<Document> {
    return value.map((x)=>from_candid_Document_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NotificationPublic>): Array<NotificationPublic> {
    return value.map((x)=>from_candid_NotificationPublic_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProjectPublic>): Array<ProjectPublic> {
    return value.map((x)=>from_candid_ProjectPublic_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TransactionPublic>): Array<TransactionPublic> {
    return value.map((x)=>from_candid_TransactionPublic_n52(_uploadFile, _downloadFile, x));
}
function to_candid_AddProjectInput_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddProjectInput): _AddProjectInput {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_AddTransactionInput_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddTransactionInput): _AddTransactionInput {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_AuditAction_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AuditAction): _AuditAction {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_AuditFilter_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AuditFilter): _AuditFilter {
    return to_candid_record_n77(_uploadFile, _downloadFile, value);
}
function to_candid_CheckDetailsPublic_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CheckDetailsPublic): _CheckDetailsPublic {
    return to_candid_record_n47(_uploadFile, _downloadFile, value);
}
function to_candid_CheckStatus_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CheckStatus): _CheckStatus {
    return to_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function to_candid_CoaReportStatus_n98(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoaReportStatus): _CoaReportStatus {
    return to_candid_variant_n99(_uploadFile, _downloadFile, value);
}
function to_candid_CoaReportType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoaReportType): _CoaReportType {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_NotificationType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): _NotificationType {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_ProjectStatus_n101(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): _ProjectStatus {
    return to_candid_variant_n102(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n68(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionStatus_n103(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): _SubscriptionStatus {
    return to_candid_variant_n104(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionFilter_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionFilter): _TransactionFilter {
    return to_candid_record_n91(_uploadFile, _downloadFile, value);
}
function to_candid_TransactionType_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): _TransactionType {
    return to_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Timestamp | null): [] | [_Timestamp] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionId | null): [] | [_TransactionId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectId | null): [] | [_ProjectId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AuditFilter | null): [] | [_AuditFilter] {
    return value === null ? candid_none() : candid_some(to_candid_AuditFilter_n76(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionFilter | null): [] | [_TransactionFilter] {
    return value === null ? candid_none() : candid_some(to_candid_TransactionFilter_n90(_uploadFile, _downloadFile, value));
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endDate?: Timestamp;
    name: string;
    description: string;
    budgetAllocation: bigint;
    startDate: Timestamp;
}): {
    endDate: [] | [_Timestamp];
    name: string;
    description: string;
    budgetAllocation: bigint;
    startDate: _Timestamp;
} {
    return {
        endDate: value.endDate ? candid_some(value.endDate) : candid_none(),
        name: value.name,
        description: value.description,
        budgetAllocation: value.budgetAllocation,
        startDate: value.startDate
    };
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentMethod: PaymentMethod;
    date: Timestamp;
    description: string;
    projectId?: ProjectId;
    checkDetails?: CheckDetailsPublic;
    txType: TransactionType;
    receiptId?: DocumentId;
    amount: bigint;
    supplierId?: SupplierId;
}): {
    paymentMethod: _PaymentMethod;
    date: _Timestamp;
    description: string;
    projectId: [] | [_ProjectId];
    checkDetails: [] | [_CheckDetailsPublic];
    txType: _TransactionType;
    receiptId: [] | [_DocumentId];
    amount: bigint;
    supplierId: [] | [_SupplierId];
} {
    return {
        paymentMethod: to_candid_PaymentMethod_n44(_uploadFile, _downloadFile, value.paymentMethod),
        date: value.date,
        description: value.description,
        projectId: value.projectId ? candid_some(value.projectId) : candid_none(),
        checkDetails: value.checkDetails ? candid_some(to_candid_CheckDetailsPublic_n46(_uploadFile, _downloadFile, value.checkDetails)) : candid_none(),
        txType: to_candid_TransactionType_n50(_uploadFile, _downloadFile, value.txType),
        receiptId: value.receiptId ? candid_some(value.receiptId) : candid_none(),
        amount: value.amount,
        supplierId: value.supplierId ? candid_some(value.supplierId) : candid_none()
    };
}
function to_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: CheckStatus;
    bankName: string;
    checkNumber?: string;
    checkDate: Timestamp;
    payee: string;
    purpose: string;
}): {
    status: _CheckStatus;
    bankName: string;
    checkNumber: [] | [string];
    checkDate: _Timestamp;
    payee: string;
    purpose: string;
} {
    return {
        status: to_candid_CheckStatus_n48(_uploadFile, _downloadFile, value.status),
        bankName: value.bankName,
        checkNumber: value.checkNumber ? candid_some(value.checkNumber) : candid_none(),
        checkDate: value.checkDate,
        payee: value.payee,
        purpose: value.purpose
    };
}
function to_candid_record_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    action?: AuditAction;
    userId?: UserId;
    toDate?: Timestamp;
    fromDate?: Timestamp;
}): {
    action: [] | [_AuditAction];
    userId: [] | [_UserId];
    toDate: [] | [_Timestamp];
    fromDate: [] | [_Timestamp];
} {
    return {
        action: value.action ? candid_some(to_candid_AuditAction_n7(_uploadFile, _downloadFile, value.action)) : candid_none(),
        userId: value.userId ? candid_some(value.userId) : candid_none(),
        toDate: value.toDate ? candid_some(value.toDate) : candid_none(),
        fromDate: value.fromDate ? candid_some(value.fromDate) : candid_none()
    };
}
function to_candid_record_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paymentMethod?: PaymentMethod;
    toDate?: Timestamp;
    projectId?: ProjectId;
    fromDate?: Timestamp;
    txType?: TransactionType;
}): {
    paymentMethod: [] | [_PaymentMethod];
    toDate: [] | [_Timestamp];
    projectId: [] | [_ProjectId];
    fromDate: [] | [_Timestamp];
    txType: [] | [_TransactionType];
} {
    return {
        paymentMethod: value.paymentMethod ? candid_some(to_candid_PaymentMethod_n44(_uploadFile, _downloadFile, value.paymentMethod)) : candid_none(),
        toDate: value.toDate ? candid_some(value.toDate) : candid_none(),
        projectId: value.projectId ? candid_some(value.projectId) : candid_none(),
        fromDate: value.fromDate ? candid_some(value.fromDate) : candid_none(),
        txType: value.txType ? candid_some(to_candid_TransactionType_n50(_uploadFile, _downloadFile, value.txType)) : candid_none()
    };
}
function to_candid_variant_n102(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProjectStatus): {
    completed: null;
} | {
    ongoing: null;
} | {
    planning: null;
} {
    return value == ProjectStatus.completed ? {
        completed: null
    } : value == ProjectStatus.ongoing ? {
        ongoing: null
    } : value == ProjectStatus.planning ? {
        planning: null
    } : value;
}
function to_candid_variant_n104(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): {
    trial: null;
} | {
    active: null;
} | {
    expired: null;
} {
    return value == SubscriptionStatus.trial ? {
        trial: null
    } : value == SubscriptionStatus.active ? {
        active: null
    } : value == SubscriptionStatus.expired ? {
        expired: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoaReportType): {
    notesToFS: null;
} | {
    inventoryReport: null;
} | {
    asrp: null;
} | {
    qsrp: null;
} | {
    raaf: null;
} | {
    budgetVsActual: null;
} {
    return value == CoaReportType.notesToFS ? {
        notesToFS: null
    } : value == CoaReportType.inventoryReport ? {
        inventoryReport: null
    } : value == CoaReportType.asrp ? {
        asrp: null
    } : value == CoaReportType.qsrp ? {
        qsrp: null
    } : value == CoaReportType.raaf ? {
        raaf: null
    } : value == CoaReportType.budgetVsActual ? {
        budgetVsActual: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NotificationType): {
    budgetAlert: null;
} | {
    coaDeadline: null;
} | {
    missingReceipt: null;
} | {
    pendingApproval: null;
} | {
    subscriptionReminder: null;
} {
    return value == NotificationType.budgetAlert ? {
        budgetAlert: null
    } : value == NotificationType.coaDeadline ? {
        coaDeadline: null
    } : value == NotificationType.missingReceipt ? {
        missingReceipt: null
    } : value == NotificationType.pendingApproval ? {
        pendingApproval: null
    } : value == NotificationType.subscriptionReminder ? {
        subscriptionReminder: null
    } : value;
}
function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    cash: null;
} | {
    check: null;
} | {
    bankTransfer: null;
} | {
    gcash: null;
} {
    return value == PaymentMethod.cash ? {
        cash: null
    } : value == PaymentMethod.check ? {
        check: null
    } : value == PaymentMethod.bankTransfer ? {
        bankTransfer: null
    } : value == PaymentMethod.gcash ? {
        gcash: null
    } : value;
}
function to_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CheckStatus): {
    cancelled: null;
} | {
    issued: null;
} | {
    pendingIssuance: null;
} | {
    cleared: null;
} {
    return value == CheckStatus.cancelled ? {
        cancelled: null
    } : value == CheckStatus.issued ? {
        issued: null
    } : value == CheckStatus.pendingIssuance ? {
        pendingIssuance: null
    } : value == CheckStatus.cleared ? {
        cleared: null
    } : value;
}
function to_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TransactionType): {
    projectExpenses: null;
} | {
    expenses: null;
} | {
    cashAdvance: null;
} | {
    reimbursement: null;
} | {
    income: null;
} {
    return value == TransactionType.projectExpenses ? {
        projectExpenses: null
    } : value == TransactionType.expenses ? {
        expenses: null
    } : value == TransactionType.cashAdvance ? {
        cashAdvance: null
    } : value == TransactionType.reimbursement ? {
        reimbursement: null
    } : value == TransactionType.income ? {
        income: null
    } : value;
}
function to_candid_variant_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    chairperson: null;
} | {
    treasurer: null;
} {
    return value == Role.chairperson ? {
        chairperson: null
    } : value == Role.treasurer ? {
        treasurer: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AuditAction): {
    generateReport: null;
} | {
    deleteTransaction: null;
} | {
    other: null;
} | {
    editTransaction: null;
} | {
    login: null;
} | {
    addTransaction: null;
} {
    return value == AuditAction.generateReport ? {
        generateReport: null
    } : value == AuditAction.deleteTransaction ? {
        deleteTransaction: null
    } : value == AuditAction.other ? {
        other: null
    } : value == AuditAction.editTransaction ? {
        editTransaction: null
    } : value == AuditAction.login ? {
        login: null
    } : value == AuditAction.addTransaction ? {
        addTransaction: null
    } : value;
}
function to_candid_variant_n99(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CoaReportStatus): {
    pendingReview: null;
} | {
    submitted: null;
} | {
    needsRevision: null;
} | {
    approved: null;
} | {
    draft: null;
} {
    return value == CoaReportStatus.pendingReview ? {
        pendingReview: null
    } : value == CoaReportStatus.submitted ? {
        submitted: null
    } : value == CoaReportStatus.needsRevision ? {
        needsRevision: null
    } : value == CoaReportStatus.approved ? {
        approved: null
    } : value == CoaReportStatus.draft ? {
        draft: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
